files:
  - camera.py
  - main.py
  - model.cvimodel
  - model.mud
id: rcj_uart_ai
name: RCJ Ball Detect
version: 2.1.0
author: brendan-liang
icon: ''
desc: RCJ ball, goal and wall detection with UART, made with MaixHub AI.
