files:
  - camera.py
  - main.py
  - model.cvimodel
  - model.mud
  - screen-2-world-polar.npy
id: rcj_uart_ai
name: RCJ Ball Detect
version: 3.0.0
author: brendan-liang
icon: ''
desc: RCJ ball, goal and line detection with UART, made with MaixHub AI.
